name: west_sea
description: A new Flutter project.

publish_to: 'none'
version: 1.0.6+7

environment:
  sdk: '>=2.18.1 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  flutter_staggered_grid_view: ^0.6.2
  url_launcher: ^6.1.7
  flutter_advanced_drawer: ^1.3.2
  share_plus: ^6.3.0
  flutter_native_splash: ^2.2.16
  google_mobile_ads: ^2.3.0
  firebase_core: ^2.4.1
  firebase_database: ^10.0.9
  flutter_svg: ^1.1.6
  fluttertoast: ^8.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.11.0"

flutter:
  uses-material-design: true
  assets:
    - assets/

  fonts:
    - family: AppIcons
      fonts:
        - asset: assets/AppIcons.ttf
    - family: Dice
      fonts:
        - asset: assets/Dice.ttf

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/icon.jpg
  android_12:
    image: assets/icon.jpg
    color: "#FFFFFF"

flutter_icons:
  android: true
  image_path: "assets/icon.jpg"
  min_sdk_android: 21
  windows:
    generate: true
    image_path: "assets/icon.jpg"
    icon_size: 48
