/// Flutter icons Dice
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Dice
///      fonts:
///       - asset: fonts/Dice.ttf
///
///
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
// ignore_for_file: constant_identifier_names

import 'package:flutter/widgets.dart';

class Dice {
  Dice._();

  static const _kFontFam = 'Dice';
  static const String? _kFontPkg = null;

  static const IconData dice_5 =
      IconData(0xf523, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dice_4 =
      IconData(0xf524, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dice_1 =
      IconData(0xf525, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dice_6 =
      IconData(0xf526, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dice_3 =
      IconData(0xf527, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dice_2 =
      IconData(0xf528, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
