// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBta3YUChBiFyJHgNzmZefvinUITSfL_O4',
    appId: '1:734593698529:web:e1d2ee44c839a571a605a0',
    messagingSenderId: '734593698529',
    projectId: 'west-sea-tv-5144e',
    authDomain: 'west-sea-tv-5144e.firebaseapp.com',
    databaseURL: 'https://west-sea-tv-5144e-default-rtdb.firebaseio.com',
    storageBucket: 'west-sea-tv-5144e.appspot.com',
    measurementId: 'G-3RE4ZHMER6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaSoKL7mbqbL2MApZbPkfZ_CBkeZNuXyU',
    appId: '1:734593698529:android:b1f54cf71273e63da605a0',
    messagingSenderId: '734593698529',
    projectId: 'west-sea-tv-5144e',
    databaseURL: 'https://west-sea-tv-5144e-default-rtdb.firebaseio.com',
    storageBucket: 'west-sea-tv-5144e.appspot.com',
  );
}
